const imgUrl = {
  close:'./img/close.png',
  logo:'./img/logo.png',
  login_bg:'./img/login_bg.png',
  home_bg_1:'./img/home_bg_1.png',
  home_bg_2:'./img/home_bg_2.png',
  home_btn:'./img/home_btn.png',
  left_icon_1:'./img/left_icon_1.png',
  left_icon_2:'./img/left_icon_2.png',
  left_icon_3:'./img/left_icon_3.png',
  left_icon_4:'./img/left_icon_4.png',
  left_icon_5:'./img/left_icon_5.png',
  left_icon_6:'./img/left_icon_6.png',
  left_icon_1_a: './img/left_icon_1_active.png',
  left_icon_2_a: './img/left_icon_2_active.png',
  left_icon_3_a: './img/left_icon_3_active.png',
  left_icon_4_a: './img/left_icon_4_active.png',
  left_icon_5_a: './img/left_icon_5_active.png',
  // left_icon_6_a: './img/left_icon_6_active.png',
  logout:'./img/logout.png',
  upload_icon:'./img/upload_icon.png',
  add_tr: './img/add_tr.png',
  import_icon: './img/import_icon.png',
  poc_time: './img/poc_time.png',
  poc_del: './img/poc_del.png',
  search: './img/search.png',
  menu_more: './img/menu_more.png',
  cnv_icon: './img/cnv_icon.png',
  down_calc: './img/down_calc.png',
  helper: './img/helper.png',
  lang: './img/lang.png',
  prev_page: './img/prev_page.png',
  next_page: './img/next_page.png',
  go_conver: './img/go_conver.png',
  car: './img/car.png',
  user: './img/user.png',
  help: './img/help.png',
  header_logo: './img/header_logo.png',
  switch:'./img/switch.png',
  detail_wechat: './img/detail_wechat.png',
}

export default imgUrl