const imgUrl = {
  close:'./img/close.png',
  logo:'./img/logo.png',
  login_bg:'./img/login_bg.png',
  home_bg_1:'./img/home_bg_1.png',
  home_bg_2:'./img/home_bg_2.png',
  home_btn:'./img/home_btn.png',
  left_icon_1:'./img/left_icon_1.png',
  left_icon_2:'./img/left_icon_2.png',
  left_icon_3:'./img/left_icon_3.png',
  left_icon_4:'./img/left_icon_4.png',
  left_icon_5:'./img/left_icon_5.png',
  left_icon_6:'./img/left_icon_6.png',
  logout:'./img/logout.png',
  upload_icon_1:'./img/upload_icon_1.png',
  upload_icon_2:'./img/upload_icon_2.png',
  add_tr: './img/add_tr.png',
  import_icon: './img/import_icon.png',
  poc_time: './img/poc_time.png',
  poc_del: './img/poc_del.png',
  search: './img/search.png',
  menu_more: './img/menu_more.png',
  cnv_icon: './img/cnv_icon.png',
  down_calc: './img/down_calc.png',
  helper: './img/helper.png',
  lang: './img/lang.png',
}

export default imgUrl